/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleList: typeof import('./src/components/Article/articleList.vue')['default']
    AssetsDetails: typeof import('./src/components/Assets/assetsDetails.vue')['default']
    Banner: typeof import('./src/components/Home/banner.vue')['default']
    BindInviteCode: typeof import('./src/components/Home/bindInviteCode.vue')['default']
    BuyPartner: typeof import('./src/components/Partner/buyPartner.vue')['default']
    ChildrenHeader: typeof import('./src/components/ChildrenHeader.vue')['default']
    ContactUs: typeof import('./src/components/Home/contactUs.vue')['default']
    EarnDetail: typeof import('./src/components/Pledge/earnDetail.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Fuel: typeof import('./src/components/Pledge/fuel.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    More: typeof import('./src/components/Home/more.vue')['default']
    MyAssets: typeof import('./src/components/Assets/myAssets.vue')['default']
    Pairs: typeof import('./src/components/Pledge/pairs.vue')['default']
    PartnerTab: typeof import('./src/components/Partner/partnerTab.vue')['default']
    PledgeInfo: typeof import('./src/components/Pledge/pledgeInfo.vue')['default']
    PledgePop: typeof import('./src/components/Pledge/pledgePop.vue')['default']
    PledgeTab: typeof import('./src/components/Pledge/pledgeTab.vue')['default']
    Recharge: typeof import('./src/components/My/recharge.vue')['default']
    Reinvestment: typeof import('./src/components/Pledge/reinvestment.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swap: typeof import('./src/components/My/swap.vue')['default']
    TabList: typeof import('./src/components/Home/tabList.vue')['default']
    TeamInfo: typeof import('./src/components/Team/teamInfo.vue')['default']
    TeamMember: typeof import('./src/components/Team/teamMember.vue')['default']
    Transfer: typeof import('./src/components/My/transfer.vue')['default']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanProgress: typeof import('vant/es')['Progress']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
    WalletInfo: typeof import('./src/components/My/walletInfo.vue')['default']
    Withdraw: typeof import('./src/components/My/withdraw.vue')['default']
  }
}
